<a href="https://colab.research.google.com/github/VSBhuvana/Machine-Learning-LAB-sessions/blob/main/ML_Lab_Session_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

def load_data():
  data = pd.read_excel("/Lab Session Data.xlsx", sheet_name= "Purchase data")

  x = data [["Candies (#)", "Mangoes (Kg)", "Milk Packets (#)"]].values
  y = data["Payment (Rs)"].values

  return x,y
def find_rank(x):
  rank = np.linalg.matrix_rank(x)
  return rank

def find_cost(x, y):
  pseudo_inverse = np.linalg.pinv(x)
  cost = np.dot(pseudo_inverse, y)
  return cost

def main():
  x,y = load_data()
  rank = find_rank(x)
  cost = find_cost(x,y)
  print("feature matrix x:")
  print(x)
  print("outpyt vector y: ")
  print(y)
  print("rank of x:", rank)
  print("cost of each product: ")
  print("cosr of one candy =", cost[0])
  print("cosr of one kg mangos= ", cost[1])
  print("cosr of one milk packet= ", cost[2])
main()

feature matrix x:
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
outpyt vector y: 
[386 289 393 110 280 167 271 274 148 198]
rank of x: 3
cost of each product: 
cosr of one candy = 0.9999999999999989
cosr of one kg mangos=  54.99999999999999
cosr of one milk packet=  18.0


In [7]:
import pandas as pd
def load_data():
  data = pd.read_excel("/Lab Session Data.xlsx", sheet_name = "Purchase data")
  return data

def classify_customers(data):
  customer_class = []

  for payment in data["Payment (Rs)"]:
    if payment > 200:
      customer_class.append("RICH")
    else:
      customer_class.append("poor")
  data["Class"] = customer_class
  return data
def main():
  data = load_data()
  classified_data = classify_customers(data)
  print("customers classfied as rich or poor: ")
  print(classified_data)
main()


customers classfied as rich or poor: 
  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
0      C_1           20             6                 2           386   
1      C_2           16             3                 6           289   
2      C_3           27             6                 2           393   
3      C_4           19             1                 2           110   
4      C_5           24             4                 2           280   
5      C_6           22             1                 5           167   
6      C_7           15             4                 2           271   
7      C_8           18             4                 2           274   
8      C_9           21             1                 4           148   
9     C_10           16             2                 4           198   

   Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0         NaN         NaN         NaN         NaN         NaN  ...   
1         NaN     